name: usersideloanapp
description: "QuickLoan – Fintech Loan Application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1
  firebase_storage: ^13.1.0
  image_picker: ^1.2.1
  file_picker: ^8.0.0
  universal_html: ^2.2.4


  # 💾 Local storage
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  get: ^4.6.6

  # 🎨 UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0
  scrollable_positioned_list: ^0.3.8
  syncfusion_flutter_gauges: ^25.1.35
  dropdown_search: ^6.0.0
  flutter_staggered_animations: ^1.0.1
  lottie: ^3.1.2
  flutter_typeahead: ^5.2.0
  flutter_svg: ^2.0.10
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  

  # ⭐ Recommended for production fintech apps
  intl: ^0.19.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoloanapp.png"
  min_sdk_android: 21