// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpuEvsR-ecAa7h0LlaMvwAhdEBi72WJJU',
    appId: '1:658404527384:web:c152b42c94604451b0a26d',
    messagingSenderId: '658404527384',
    projectId: 'newuserapp-20164',
    authDomain: 'newuserapp-20164.firebaseapp.com',
    storageBucket: 'newuserapp-20164.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXEx_MbzujmuM3QKpEm_O3oGWtA55GTG8',
    appId: '1:658404527384:android:b27e73af0dede468b0a26d',
    messagingSenderId: '658404527384',
    projectId: 'newuserapp-20164',
    storageBucket: 'newuserapp-20164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBUwEyDh-TL-3xXysJJigMjWDgMkRQAEY',
    appId: '1:658404527384:ios:4d0c7a95b44350cbb0a26d',
    messagingSenderId: '658404527384',
    projectId: 'newuserapp-20164',
    storageBucket: 'newuserapp-20164.firebasestorage.app',
    iosBundleId: 'com.example.usersideloanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBUwEyDh-TL-3xXysJJigMjWDgMkRQAEY',
    appId: '1:658404527384:ios:4d0c7a95b44350cbb0a26d',
    messagingSenderId: '658404527384',
    projectId: 'newuserapp-20164',
    storageBucket: 'newuserapp-20164.firebasestorage.app',
    iosBundleId: 'com.example.usersideloanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpuEvsR-ecAa7h0LlaMvwAhdEBi72WJJU',
    appId: '1:658404527384:web:553600048f6f64ebb0a26d',
    messagingSenderId: '658404527384',
    projectId: 'newuserapp-20164',
    authDomain: 'newuserapp-20164.firebaseapp.com',
    storageBucket: 'newuserapp-20164.firebasestorage.app',
  );
}
