name: usersideloanapp
description: "QuickLoan – Fintech Loan Application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1
  firebase_storage: ^13.1.0
  image_picker: ^1.2.1
  file_picker: ^6.1.1
  universal_html: ^2.2.4


  # 💾 Local storage
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  get: ^4.6.6

  # 🎨 UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  fl_chart: ^0.68.0

  # ⭐ Recommended for production fintech apps
  intl: ^0.19.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
